export interface Vendor {
  id: string;
  vendor_name: string;
  what_they_sell: string;
  location: string;
  hours: string;
  category: string;
  upi_id?: string;
  whatsapp_number?: string;
  registered_by: string;
  submission_timestamp: string;
  status: 'new' | 'active' | 'featured';
  rating?: number;
  reviews?: number;
  profile_url?: string;
  initials?: string;
  color?: string;
  photo_url?: string;
  owner_photo_url?: string;
  shop_photo_url?: string;
  views?: number;
  last_viewed_timestamp?: string;
}

const COLORS = ['#F97316', '#16A34A', '#2563EB', '#7C3AED', '#DB2777', '#0891B2'];

function getInitials(name: string): string {
  return name.split(' ').slice(0, 2).map(w => w[0]).join('').toUpperCase();
}

function getColor(name: string): string {
  let hash = 0;
  for (let i = 0; i < name.length; i++) hash = name.charCodeAt(i) + ((hash << 5) - hash);
  return COLORS[Math.abs(hash) % COLORS.length];
}

function daysAgo(d: number): string {
  return new Date(Date.now() - d * 24 * 60 * 60 * 1000).toISOString();
}

// In-memory store — persists for the lifetime of the server process
const vendors: Vendor[] = [
  // ── GL Bajaj College Area ──────────────────────────────────────
  {
    id: 'raju-chai-stall',
    vendor_name: "Raju's Chai Stall",
    what_they_sell: 'Chai (₹10), Samosa (₹20), Bun Maska (₹15), Cold Drink (₹30)',
    location: 'Opposite Alpha 1 Metro Gate 2, Greater Noida',
    hours: '6 AM to 10 PM, Monday to Saturday',
    category: 'Chai & Snacks',
    upi_id: 'raju.chai@paytm',
    whatsapp_number: '9800000001',
    registered_by: 'Rohit Sharma, GL Bajaj Student',
    submission_timestamp: daysAgo(10),
    status: 'featured',
    rating: 4.8,
    reviews: 92,
    profile_url: '/raju-chai-stall',
    initials: 'RC',
    color: '#F97316',
    photo_url: '/assets/vendors/shop-tea-stall.jpg',
    owner_photo_url: '/assets/vendors/owner-amritsar.jpg',
    shop_photo_url: '/assets/vendors/shop-tea-apparatus.jpg',
  },
  {
    id: 'priya-sabziwali',
    vendor_name: 'Priya Devi Sabziwali',
    what_they_sell: 'Fresh vegetables (₹30/kg), Seasonal fruits (₹40/kg), Tomatoes (₹25/kg)',
    location: 'Knowledge Park III, Near Bus Stand, Greater Noida',
    hours: '6 AM to 1 PM, Daily',
    category: 'Sabzi & Fruits',
    upi_id: 'priya.sabzi@upi',
    whatsapp_number: '9800000002',
    registered_by: 'Anjali Verma, GL Bajaj Student',
    submission_timestamp: daysAgo(9),
    status: 'featured',
    rating: 4.6,
    reviews: 38,
    profile_url: '/priya-sabziwali',
    initials: 'PD',
    color: '#16A34A',
    photo_url: '/assets/vendors/shop-street-food.jpg',
    owner_photo_url: '/assets/vendors/owner-yogurt.jpg',
    shop_photo_url: '/assets/vendors/shop-tea-stall.jpg',
  },
  {
    id: 'mohan-momos-corner',
    vendor_name: "Mohan's Momos Corner",
    what_they_sell: 'Momos (₹60), Chowmein (₹50), Soup (₹40), Fried Momos (₹70)',
    location: 'GL Bajaj College Main Gate, Knowledge Park II, Greater Noida',
    hours: '11 AM to 9 PM, Daily',
    category: 'Street Food',
    upi_id: 'mohan.momos@gpay',
    whatsapp_number: '9800000003',
    registered_by: 'Vikram Tiwari, GL Bajaj Student',
    submission_timestamp: daysAgo(8),
    status: 'featured',
    rating: 4.5,
    reviews: 61,
    initials: 'MM',
    color: '#2563EB',
    photo_url: '/assets/vendors/shop-tea-apparatus.jpg',
    owner_photo_url: '/assets/vendors/owner-street-vendor.jpg',
    shop_photo_url: '/assets/vendors/shop-street-food.jpg',
  },
  {
    id: 'suresh-paan-snacks',
    vendor_name: 'Suresh Paan & Snacks',
    what_they_sell: 'Paan (₹15), Cigarettes (₹15), Chips (₹20), Cold Drinks (₹30)',
    location: 'Pari Chowk, Greater Noida',
    hours: '8 AM to 11 PM, Daily',
    category: 'Paan & More',
    upi_id: 'suresh.paan@phonepe',
    whatsapp_number: '9800000004',
    registered_by: 'Deepak Singh, GL Bajaj Student',
    submission_timestamp: daysAgo(7),
    status: 'active',
    rating: 4.3,
    reviews: 24,
    initials: 'SP',
    color: '#7C3AED',
    photo_url: 'https://images.pexels.com/photos/3729168/pexels-photo-3729168.jpeg?w=600&h=400&fit=crop',
    owner_photo_url: 'https://images.pexels.com/photos/1108101/pexels-photo-1108101.jpeg?w=200&h=200&fit=crop',
    shop_photo_url: 'https://images.pexels.com/photos/3729168/pexels-photo-3729168.jpeg?w=800&h=600&fit=crop',
  },
  {
    id: 'bablu-maggi-point',
    vendor_name: "Bablu's Maggi Point",
    what_they_sell: 'Maggi (₹40), Masala Maggi (₹50), Bread Omelette (₹35), Chai (₹10)',
    location: 'Near GL Bajaj Hostel Gate, Knowledge Park II, Greater Noida',
    hours: '7 AM to 11 PM, Daily',
    category: 'Street Food',
    upi_id: 'bablu.maggi@paytm',
    whatsapp_number: '9811223344',
    registered_by: 'Sneha Rawat, GL Bajaj Student',
    submission_timestamp: daysAgo(6),
    status: 'active',
    rating: 4.4,
    reviews: 47,
    initials: 'BM',
    color: '#DB2777',
    photo_url: 'https://images.pexels.com/photos/1126736/pexels-photo-1126736.jpeg?w=600&h=400&fit=crop',
    owner_photo_url: 'https://images.pexels.com/photos/1181690/pexels-photo-1181690.jpeg?w=200&h=200&fit=crop',
    shop_photo_url: 'https://images.pexels.com/photos/1126736/pexels-photo-1126736.jpeg?w=800&h=600&fit=crop',
  },
  {
    id: 'kamla-juice-corner',
    vendor_name: 'Kamla Ji Juice Corner',
    what_they_sell: 'Sugarcane Juice (₹20), Mixed Fruit Juice (₹40), Nimbu Pani (₹20), Lassi (₹40)',
    location: 'Alpha 2 Market, Greater Noida',
    hours: '9 AM to 8 PM, Daily',
    category: 'Chai & Snacks',
    upi_id: 'kamla.juice@upi',
    whatsapp_number: '9822334455',
    registered_by: 'Priya Negi, GL Bajaj Student',
    submission_timestamp: daysAgo(5),
    status: 'active',
    rating: 4.7,
    reviews: 33,
    initials: 'KJ',
    color: '#0891B2',
    photo_url: 'https://images.unsplash.com/photo-1595521624536-62b92e4f2c53?w=600&h=400&fit=crop&q=80',
    owner_photo_url: 'https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=200&h=200&fit=crop&q=80',
    shop_photo_url: 'https://images.unsplash.com/photo-1595521624536-62b92e4f2c53?w=800&h=600&fit=crop&q=80',
  },
  {
    id: 'ramesh-sandwich-wala',
    vendor_name: 'Ramesh Sandwich Wala',
    what_they_sell: 'Veg Sandwich (₹50), Cheese Sandwich (₹70), Club Sandwich (₹80), Cold Coffee (₹40)',
    location: 'Opposite GL Bajaj College, Knowledge Park II',
    hours: '8 AM to 8 PM, Monday to Saturday',
    category: 'Street Food',
    upi_id: 'ramesh.sandwich@gpay',
    whatsapp_number: '9876543210',
    registered_by: 'Arjun Pandey, GL Bajaj Student',
    submission_timestamp: daysAgo(4),
    status: 'active',
    rating: 4.2,
    reviews: 19,
    initials: 'RS',
    color: '#F97316',
    photo_url: 'https://images.unsplash.com/photo-1528366521425-8f66a3d518da?w=600&h=400&fit=crop&q=80',
    owner_photo_url: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=200&h=200&fit=crop&q=80',
    shop_photo_url: 'https://images.unsplash.com/photo-1528366521425-8f66a3d518da?w=800&h=600&fit=crop&q=80',
  },
  {
    id: 'sunita-paratha-dhaba',
    vendor_name: 'Sunita Devi Paratha Dhaba',
    what_they_sell: 'Aloo Paratha (₹40), Gobhi Paratha (₹45), Paneer Paratha (₹60), Lassi (₹30)',
    location: 'Sector Beta 2, Near GL Bajaj, Greater Noida',
    hours: '7 AM to 12 PM, Daily',
    category: 'Street Food',
    upi_id: 'sunita.paratha@paytm',
    whatsapp_number: '9876512345',
    registered_by: 'Meena Joshi, GL Bajaj Student',
    submission_timestamp: daysAgo(3),
    status: 'active',
    rating: 4.6,
    reviews: 55,
    initials: 'SD',
    color: '#16A34A',
    photo_url: 'https://images.unsplash.com/photo-1644074063117-e40ca61a575f?w=600&h=400&fit=crop&q=80',
    owner_photo_url: 'https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=200&h=200&fit=crop&q=80',
    shop_photo_url: 'https://images.unsplash.com/photo-1644074063117-e40ca61a575f?w=800&h=600&fit=crop&q=80',
  },
  {
    id: 'vikash-pizza-hut',
    vendor_name: "Vikash's Pizza Station",
    owner_photo_url: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=200&h=200&fit=crop&q=80',
    shop_photo_url: 'https://images.unsplash.com/photo-1604068549290-dea0e4a305ca?w=800&h=600&fit=crop&q=80',
    what_they_sell: 'Margherita Pizza (₹150), Paneer Pizza (₹180), Veggie Pizza (₹160), Garlic Bread (₹80)',
    location: 'Knowledge Park III, Near Wave City, Greater Noida',
    hours: '11 AM to 11 PM, Daily',
    category: 'Street Food',
    upi_id: 'vikash.pizza@gpay',
    whatsapp_number: '9988776633',
    registered_by: 'Vikash Kumar, GL Bajaj Alumni',
    submission_timestamp: daysAgo(2),
    status: 'featured',
    rating: 4.7,
    reviews: 102,
    initials: 'VP',
    color: '#F97316',
    photo_url: 'https://images.unsplash.com/photo-1604068549290-dea0e4a305ca?w=600&h=400&fit=crop&q=80',
    owner_photo_url: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=200&h=200&fit=crop&q=80',
    shop_photo_url: 'https://images.unsplash.com/photo-1604068549290-dea0e4a305ca?w=800&h=600&fit=crop&q=80',
  },
  {
    id: 'neha-fast-food',
    vendor_name: "Neha's Fast Food Counter",
    what_they_sell: 'Pav Bhaji (₹50), Vada Pav (₹35), Chole Bhature (₹60), Dahi Vada (₹40)',
    location: 'Sector Omega I, Near Alpha 1 Gate, Greater Noida',
    hours: '10 AM to 10 PM, Daily',
    category: 'Street Food',
    upi_id: 'neha.fastfood@paytm',
    whatsapp_number: '9876543221',
    registered_by: 'Neha Gupta, GL Bajaj Student',
    submission_timestamp: daysAgo(1),
    status: 'featured',
    rating: 4.8,
    reviews: 145,
    initials: 'NF',
    color: '#DB2777',
    photo_url: 'https://images.unsplash.com/photo-1585238341710-57b0e4bea7ee?w=600&h=400&fit=crop&q=80',
    owner_photo_url: 'https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=200&h=200&fit=crop&q=80',
    shop_photo_url: 'https://images.unsplash.com/photo-1585238341710-57b0e4bea7ee?w=800&h=600&fit=crop&q=80',
  },
  {
    id: 'arun-ice-cream-parlor',
    vendor_name: 'Arun Ice Cream Parlor',
    what_they_sell: 'Vanilla (₹30), Chocolate (₹35), Kulfi (₹25), Ice Cream Sandwich (₹40)',
    location: 'Shopping Complex, Knowledge Park II, Greater Noida',
    hours: '12 PM to 10 PM, Daily',
    category: 'Chai & Snacks',
    upi_id: 'arun.icecream@upi',
    whatsapp_number: '9765432198',
    registered_by: 'Arun Singh, Local Entrepreneur',
    submission_timestamp: daysAgo(2),
    status: 'active',
    rating: 4.5,
    reviews: 78,
    initials: 'AI',
    color: '#2563EB',
    photo_url: 'https://images.unsplash.com/photo-1563805042-7684c019e1cb?w=600&h=400&fit=crop&q=80',
    owner_photo_url: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=200&h=200&fit=crop&q=80',
    shop_photo_url: 'https://images.unsplash.com/photo-1568901346375-23c9450c58cd?w=800&h=600&fit=crop&q=80',
  },
  {
    id: 'raj-burger-station',
    vendor_name: 'Raj Burger Station',
    what_they_sell: 'Veg Burger (₹60), Paneer Burger (₹80), Cheese Burger (₹70), Fries (₹40)',
    location: 'Opposite GL Bajaj Gate, Knowledge Park II, Greater Noida',
    hours: '11 AM to 10 PM, Monday to Sunday',
    category: 'Street Food',
    upi_id: 'raj.burger@gpay',
    whatsapp_number: '9654321876',
    registered_by: 'Rajesh Kumar, GL Bajaj Resident',
    submission_timestamp: daysAgo(1),
    status: 'featured',
    rating: 4.9,
    reviews: 168,
    initials: 'RB',
    color: '#7C3AED',
    photo_url: '/assets/vendors/shop-street-food.jpg',
    owner_photo_url: '/assets/vendors/owner-amritsar.jpg',
    shop_photo_url: '/assets/vendors/shop-tea-stall.jpg',
  },
  {
    id: 'seema-clothing-store',
    vendor_name: 'Seema Clothing Hub',
    what_they_sell: 'Jeans (₹400-800), T-Shirts (₹200-500), Kurtis (₹300-700), Sarees (₹500-1500)',
    location: 'Sector Alpha 1, Near Shopping Mall, Greater Noida',
    hours: '10 AM to 9 PM, Daily',
    category: 'Retail',
    upi_id: 'seema.clothing@paytm',
    whatsapp_number: '9543216789',
    registered_by: 'Seema Sharma, GL Bajaj Alumna',
    submission_timestamp: daysAgo(3),
    status: 'active',
    rating: 4.4,
    reviews: 91,
    initials: 'SC',
    color: '#0891B2',
    photo_url: 'https://images.pexels.com/photos/2769274/pexels-photo-2769274.jpeg?w=600&h=400&fit=crop',
    owner_photo_url: 'https://images.pexels.com/photos/1181690/pexels-photo-1181690.jpeg?w=200&h=200&fit=crop',
    shop_photo_url: 'https://images.pexels.com/photos/2769274/pexels-photo-2769274.jpeg?w=800&h=600&fit=crop',
  },
  // ── Noida Sector 18 / 62 / 63 ─────────────────────────────────
  {
    id: 'chhotu-chai-sector18',
    vendor_name: "Chhotu Bhaiya's Chai",
    what_they_sell: 'Cutting Chai (₹10), Ginger Chai (₹12), Samosa (₹20), Biscuits (₹5)',
    location: 'Sector 18 Metro Station Exit 1, Noida',
    hours: '6 AM to 9 PM, Daily',
    category: 'Chai & Snacks',
    upi_id: 'chhotu.chai@phonepe',
    whatsapp_number: '9988776655',
    registered_by: 'Rahul Gupta, Noida Resident',
    submission_timestamp: daysAgo(12),
    status: 'active',
    rating: 4.5,
    reviews: 78,
    initials: 'CB',
    color: '#F97316',
  },
  {
    id: 'lallan-chaat-bhandar',
    vendor_name: 'Lallan Ji Chaat Bhandar',
    what_they_sell: 'Pani Puri (₹30), Bhelpuri (₹30), Aloo Tikki (₹40), Dahi Puri (₹40)',
    location: 'Atta Market, Sector 18, Noida',
    hours: '4 PM to 10 PM, Daily',
    category: 'Street Food',
    upi_id: 'lallan.chaat@gpay',
    registered_by: 'Kavita Mishra, Noida Resident',
    submission_timestamp: daysAgo(14),
    status: 'active',
    rating: 4.7,
    reviews: 112,
    initials: 'LC',
    color: '#DB2777',
  },
  {
    id: 'guddu-fruit-wala-62',
    vendor_name: 'Guddu Fruit Wala',
    what_they_sell: 'Watermelon (₹20/kg), Mango (₹60/kg), Banana (₹40/dozen), Mixed Fruits (₹50/kg)',
    location: 'Sector 62, Near Infosys Gate, Noida',
    hours: '7 AM to 7 PM, Daily',
    category: 'Sabzi & Fruits',
    upi_id: 'guddu.fruit@paytm',
    whatsapp_number: '9871234567',
    registered_by: 'Ankit Srivastava, IT Professional',
    submission_timestamp: daysAgo(11),
    status: 'active',
    rating: 4.4,
    reviews: 29,
    initials: 'GF',
    color: '#16A34A',
  },
  {
    id: 'munna-momos-sector63',
    vendor_name: "Munna's Momos & Rolls",
    what_they_sell: 'Steam Momos (₹60), Fried Momos (₹70), Veg Roll (₹50), Paneer Roll (₹70)',
    location: 'Sector 63, Near HCL Technologies, Noida',
    hours: '12 PM to 10 PM, Daily',
    category: 'Street Food',
    upi_id: 'munna.momos@upi',
    whatsapp_number: '9765432109',
    registered_by: 'Pooja Sharma, Software Engineer',
    submission_timestamp: daysAgo(16),
    status: 'active',
    rating: 4.3,
    reviews: 44,
    initials: 'MR',
    color: '#2563EB',
  },
  {
    id: 'shyam-sabzi-sector15',
    vendor_name: 'Shyam Lal Sabziwala',
    what_they_sell: 'Onion (₹30/kg), Potato (₹25/kg), Tomato (₹30/kg), Green Vegetables (₹40/kg)',
    location: 'Sector 15A Market, Noida',
    hours: '6 AM to 2 PM, Daily',
    category: 'Sabzi & Fruits',
    upi_id: 'shyam.sabzi@phonepe',
    registered_by: 'Sunita Agarwal, Housewife',
    submission_timestamp: daysAgo(18),
    status: 'active',
    rating: 4.5,
    reviews: 67,
    initials: 'SL',
    color: '#16A34A',
  },
  {
    id: 'pappu-paan-sector19',
    vendor_name: 'Pappu Paan Corner',
    what_they_sell: 'Sweet Paan (₹20), Meetha Paan (₹25), Cigarettes (₹15), Gutka (₹10)',
    location: 'Sector 19 Market, Near DPS School, Noida',
    hours: '9 AM to 11 PM, Daily',
    category: 'Paan & More',
    registered_by: 'Ravi Kumar, Local Resident',
    submission_timestamp: daysAgo(20),
    status: 'active',
    rating: 4.1,
    reviews: 18,
    initials: 'PP',
    color: '#7C3AED',
  },
  {
    id: 'geeta-devi-poha-wali',
    vendor_name: 'Geeta Devi Poha Wali',
    what_they_sell: 'Poha (₹25), Jalebi (₹30), Chai (₹10), Upma (₹25)',
    location: 'Sector 22, Near Noida Stadium, Noida',
    hours: '7 AM to 11 AM, Daily',
    category: 'Street Food',
    upi_id: 'geeta.poha@gpay',
    registered_by: 'Neha Tiwari, Noida Resident',
    submission_timestamp: daysAgo(22),
    status: 'active',
    rating: 4.8,
    reviews: 89,
    initials: 'GP',
    color: '#DB2777',
  },

  // ── Gurgaon / Gurugram ────────────────────────────────────────
  {
    id: 'harish-chai-cyber-city',
    vendor_name: 'Harish Bhaiya Chai Wala',
    what_they_sell: 'Masala Chai (₹15), Cutting Chai (₹10), Samosa (₹20), Parle-G (₹5)',
    location: 'Cyber City DLF Phase 2, Near Rapid Metro, Gurgaon',
    hours: '7 AM to 8 PM, Monday to Saturday',
    category: 'Chai & Snacks',
    upi_id: 'harish.chai@paytm',
    whatsapp_number: '9654321098',
    registered_by: 'Amit Khanna, IT Professional',
    submission_timestamp: daysAgo(13),
    status: 'active',
    rating: 4.6,
    reviews: 134,
    initials: 'HC',
    color: '#F97316',
  },
  {
    id: 'razia-biryani-gurgaon',
    vendor_name: "Razia's Biryani Corner",
    what_they_sell: 'Veg Biryani (₹80), Egg Biryani (₹100), Raita (₹20), Cold Drink (₹30)',
    location: 'Sector 29 Food Street, Gurgaon',
    hours: '12 PM to 9 PM, Daily',
    category: 'Street Food',
    upi_id: 'razia.biryani@upi',
    whatsapp_number: '9543210987',
    registered_by: 'Farhan Sheikh, Gurgaon Resident',
    submission_timestamp: daysAgo(15),
    status: 'active',
    rating: 4.7,
    reviews: 203,
    initials: 'RB',
    color: '#0891B2',
  },
  {
    id: 'balram-sabzi-sohna-road',
    vendor_name: 'Balram Ji Sabziwala',
    what_they_sell: 'Fresh Vegetables (₹30/kg), Spinach (₹20/bunch), Coriander (₹10), Fruits (₹50/kg)',
    location: 'Sohna Road, Near Omaxe City, Gurgaon',
    hours: '6 AM to 1 PM, Daily',
    category: 'Sabzi & Fruits',
    upi_id: 'balram.sabzi@gpay',
    registered_by: 'Rekha Sharma, Housewife',
    submission_timestamp: daysAgo(17),
    status: 'active',
    rating: 4.4,
    reviews: 41,
    initials: 'BS',
    color: '#16A34A',
  },
  {
    id: 'javed-rolls-gurgaon',
    vendor_name: "Javed's Rolls & Wraps",
    what_they_sell: 'Egg Roll (₹60), Paneer Roll (₹80), Chicken Roll (₹90), Veg Roll (₹50)',
    location: 'MG Road, Near Sahara Mall, Gurgaon',
    hours: '11 AM to 11 PM, Daily',
    category: 'Street Food',
    upi_id: 'javed.rolls@phonepe',
    whatsapp_number: '9432109876',
    registered_by: 'Sana Qureshi, Gurgaon Resident',
    submission_timestamp: daysAgo(19),
    status: 'active',
    rating: 4.5,
    reviews: 88,
    initials: 'JR',
    color: '#DB2777',
  },
  {
    id: 'santosh-paan-golf-course',
    vendor_name: 'Santosh Paan Bhandar',
    what_they_sell: 'Banarasi Paan (₹30), Cigarettes (₹15), Mouth Freshener (₹10), Chips (₹20)',
    location: 'Golf Course Road, Sector 54, Gurgaon',
    hours: '10 AM to 12 AM, Daily',
    category: 'Paan & More',
    upi_id: 'santosh.paan@paytm',
    registered_by: 'Vikas Malhotra, Corporate Employee',
    submission_timestamp: daysAgo(21),
    status: 'active',
    rating: 4.2,
    reviews: 31,
    initials: 'SB',
    color: '#7C3AED',
  },
  {
    id: 'meena-chaat-huda-city',
    vendor_name: 'Meena Ji Chaat Wali',
    what_they_sell: 'Gol Gappa (₹30), Dahi Bhalla (₹50), Papdi Chaat (₹40), Aloo Tikki (₹35)',
    location: 'HUDA City Centre Metro, Gurgaon',
    hours: '3 PM to 9 PM, Daily',
    category: 'Street Food',
    upi_id: 'meena.chaat@upi',
    whatsapp_number: '9321098765',
    registered_by: 'Divya Kapoor, Gurgaon Resident',
    submission_timestamp: daysAgo(23),
    status: 'active',
    rating: 4.8,
    reviews: 156,
    initials: 'MC',
    color: '#F97316',
  },

  // ── Noida Extension / Greater Noida West ──────────────────────
  {
    id: 'dinesh-chai-gaur-city',
    vendor_name: 'Dinesh Bhaiya Chai Stall',
    what_they_sell: 'Chai (₹10), Maggi (₹40), Bread Pakora (₹30), Biscuits (₹5)',
    location: 'Gaur City 2, Near Main Gate, Noida Extension',
    hours: '6 AM to 10 PM, Daily',
    category: 'Chai & Snacks',
    upi_id: 'dinesh.chai@gpay',
    whatsapp_number: '9210987654',
    registered_by: 'Rahul Yadav, Gaur City Resident',
    submission_timestamp: daysAgo(8),
    status: 'active',
    rating: 4.3,
    reviews: 52,
    initials: 'DC',
    color: '#F97316',
  },
  {
    id: 'pushpa-sabzi-noida-ext',
    vendor_name: 'Pushpa Devi Sabziwali',
    what_they_sell: 'Vegetables (₹30/kg), Fruits (₹45/kg), Ginger Garlic (₹80/kg), Lemon (₹5 each)',
    location: 'Sector 1, Noida Extension, Near Supertech Capetown',
    hours: '7 AM to 2 PM, Daily',
    category: 'Sabzi & Fruits',
    upi_id: 'pushpa.sabzi@paytm',
    registered_by: 'Anita Chauhan, Noida Extension Resident',
    submission_timestamp: daysAgo(10),
    status: 'active',
    rating: 4.5,
    reviews: 36,
    initials: 'PS',
    color: '#16A34A',
  },
  {
    id: 'ramu-momos-noida-ext',
    vendor_name: "Ramu's Momos Stall",
    what_they_sell: 'Veg Momos (₹60), Paneer Momos (₹80), Chowmein (₹50), Manchurian (₹70)',
    location: 'Amrapali Silicon City, Noida Extension',
    hours: '12 PM to 10 PM, Daily',
    category: 'Street Food',
    upi_id: 'ramu.momos@phonepe',
    whatsapp_number: '9109876543',
    registered_by: 'Saurabh Mishra, IT Professional',
    submission_timestamp: daysAgo(6),
    status: 'active',
    rating: 4.4,
    reviews: 43,
    initials: 'RM',
    color: '#2563EB',
  },
  {
    id: 'bhola-juice-noida-ext',
    vendor_name: 'Bhola Ji Fresh Juice',
    what_they_sell: 'Sugarcane Juice (₹20), Orange Juice (₹40), Mosambi Juice (₹40), Nimbu Pani (₹20)',
    location: 'Sector 16B, Noida Extension, Near Gaur City Mall',
    hours: '9 AM to 9 PM, Daily',
    category: 'Chai & Snacks',
    upi_id: 'bhola.juice@gpay',
    registered_by: 'Priyanka Dubey, Noida Extension Resident',
    submission_timestamp: daysAgo(4),
    status: 'active',
    rating: 4.6,
    reviews: 28,
    initials: 'BJ',
    color: '#0891B2',
  },

  // ── Connaught Place / Delhi NCR ───────────────────────────────
  {
    id: 'kallu-chaat-cp',
    vendor_name: 'Kallu Ji Chaat Wala',
    what_they_sell: 'Pani Puri (₹30), Bhelpuri (₹35), Dahi Puri (₹40), Sev Puri (₹35)',
    location: 'Connaught Place, Block A, New Delhi',
    hours: '11 AM to 9 PM, Daily',
    category: 'Street Food',
    upi_id: 'kallu.chaat@upi',
    whatsapp_number: '9098765432',
    registered_by: 'Nisha Kapoor, Delhi Resident',
    submission_timestamp: daysAgo(25),
    status: 'active',
    rating: 4.7,
    reviews: 189,
    initials: 'KC',
    color: '#DB2777',
  },
  {
    id: 'shanti-devi-chai-lajpat',
    vendor_name: 'Shanti Devi Chai Wali',
    what_they_sell: 'Masala Chai (₹15), Adrak Chai (₹15), Samosa (₹20), Namkeen (₹20)',
    location: 'Lajpat Nagar Market, New Delhi',
    hours: '7 AM to 8 PM, Monday to Saturday',
    category: 'Chai & Snacks',
    upi_id: 'shanti.chai@paytm',
    registered_by: 'Monika Arora, Delhi Resident',
    submission_timestamp: daysAgo(27),
    status: 'active',
    rating: 4.5,
    reviews: 74,
    initials: 'SC',
    color: '#F97316',
  },

  // ── Faridabad ─────────────────────────────────────────────────
  {
    id: 'rajendra-sabzi-faridabad',
    vendor_name: 'Rajendra Ji Sabziwala',
    what_they_sell: 'Fresh Vegetables (₹25/kg), Seasonal Fruits (₹45/kg), Herbs (₹15/bunch)',
    location: 'Sector 16A Market, Faridabad',
    hours: '6 AM to 1 PM, Daily',
    category: 'Sabzi & Fruits',
    upi_id: 'rajendra.sabzi@phonepe',
    registered_by: 'Seema Rani, Faridabad Resident',
    submission_timestamp: daysAgo(30),
    status: 'active',
    rating: 4.3,
    reviews: 22,
    initials: 'RJ',
    color: '#16A34A',
  },
  {
    id: 'aslam-rolls-faridabad',
    vendor_name: "Aslam's Rolls & Tikka",
    what_they_sell: 'Egg Roll (₹55), Veg Roll (₹45), Tikka (₹80), Chai (₹10)',
    location: 'NIT Faridabad, Near Bus Stand',
    hours: '5 PM to 11 PM, Daily',
    category: 'Street Food',
    upi_id: 'aslam.rolls@gpay',
    whatsapp_number: '8987654321',
    registered_by: 'Imran Khan, Faridabad Resident',
    submission_timestamp: daysAgo(28),
    status: 'active',
    rating: 4.4,
    reviews: 37,
    initials: 'AR',
    color: '#0891B2',
  },

  // ── Ghaziabad ─────────────────────────────────────────────────
  {
    id: 'vinod-chai-vaishali',
    vendor_name: 'Vinod Ji Chai Stall',
    what_they_sell: 'Chai (₹10), Pakora (₹30), Samosa (₹20), Bread Pakora (₹25)',
    location: 'Vaishali Metro Station, Ghaziabad',
    hours: '6 AM to 9 PM, Daily',
    category: 'Chai & Snacks',
    upi_id: 'vinod.chai@paytm',
    whatsapp_number: '8876543210',
    registered_by: 'Sunil Tyagi, Vaishali Resident',
    submission_timestamp: daysAgo(24),
    status: 'active',
    rating: 4.4,
    reviews: 58,
    initials: 'VC',
    color: '#F97316',
  },
  {
    id: 'kamla-prasad-sabzi-gzb',
    vendor_name: 'Kamla Prasad Sabziwala',
    what_they_sell: 'Vegetables (₹30/kg), Fruits (₹50/kg), Garlic (₹100/kg), Ginger (₹80/kg)',
    location: 'Indirapuram, Near Shipra Mall, Ghaziabad',
    hours: '7 AM to 2 PM, Daily',
    category: 'Sabzi & Fruits',
    upi_id: 'kamla.sabzi@upi',
    registered_by: 'Ritu Agarwal, Indirapuram Resident',
    submission_timestamp: daysAgo(26),
    status: 'active',
    rating: 4.2,
    reviews: 19,
    initials: 'KP',
    color: '#16A34A',
  },
  {
    id: 'sonu-momos-raj-nagar',
    vendor_name: "Sonu's Momos Stall",
    what_they_sell: 'Veg Momos (₹60), Fried Momos (₹70), Chowmein (₹50), Soup (₹35)',
    location: 'Raj Nagar Extension, Near Wave City, Ghaziabad',
    hours: '1 PM to 10 PM, Daily',
    category: 'Street Food',
    upi_id: 'sonu.momos@phonepe',
    whatsapp_number: '8765432109',
    registered_by: 'Akash Garg, Raj Nagar Resident',
    submission_timestamp: daysAgo(5),
    status: 'active',
    rating: 4.3,
    reviews: 31,
    initials: 'SM',
    color: '#2563EB',
  },
  {
    id: 'devi-prasad-paan-gzb',
    vendor_name: 'Devi Prasad Paan Shop',
    what_they_sell: 'Paan (₹20), Cigarettes (₹15), Tobacco (₹10), Cold Drinks (₹30)',
    location: 'Kaushambi, Near Ansal Plaza, Ghaziabad',
    hours: '8 AM to 11 PM, Daily',
    category: 'Paan & More',
    registered_by: 'Manoj Sharma, Kaushambi Resident',
    submission_timestamp: daysAgo(29),
    status: 'active',
    rating: 4.0,
    reviews: 14,
    initials: 'DP',
    color: '#7C3AED',
  },
];

// Extended seed vendors including Greater Noida area
const SEED_VENDOR_IDS = new Set([
  'raju-chai-stall',
  'priya-sabziwali',
  'mohan-momos-corner',
  'suresh-paan-snacks',
  'bablu-maggi-point',
  'kamla-juice-corner',
  'ramesh-sandwich-wala',
  'sunita-paratha-dhaba',
  'vikash-pizza-hut',
  'neha-fast-food',
  'arun-ice-cream-parlor',
  'raj-burger-station',
]);

export function getVendors(): Vendor[] {
  return vendors
    .filter((v) => SEED_VENDOR_IDS.has(v.id) || v.id.startsWith('vendor-'))
    .map((v) => ({ ...v, views: v.views ?? 0 }))
    .sort((a, b) => new Date(b.submission_timestamp).getTime() - new Date(a.submission_timestamp).getTime());
}

export function addVendor(data: Omit<Vendor, 'id' | 'submission_timestamp' | 'status' | 'initials' | 'color'>): Vendor {
  const vendor: Vendor = {
    ...data,
    id: `vendor-${Date.now()}-${Math.random().toString(36).slice(2, 7)}`,
    submission_timestamp: new Date().toISOString(),
    status: 'new',
    initials: getInitials(data.vendor_name),
    color: getColor(data.vendor_name),
    views: 0,
  };
  vendors.unshift(vendor);
  return vendor;
}

export function incrementVendorViews(id: string): Vendor | null {
  const vendor = vendors.find((v) => v.id === id);
  if (!vendor) return null;
  vendor.views = (vendor.views || 0) + 1;
  vendor.last_viewed_timestamp = new Date().toISOString();
  return vendor;
}
